// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025-2026 Utawave

#include "Localisation.h"

namespace Localisation
{

static const char* const japaneseTranslations =
    "language: Japanese\n"
    "countries: jp\n"
    "\n"
    // ── PluginListComponent ──
    "\"Clear list\" = \"リストをクリア\"\n"
    "\"Remove all XFMTX plug-ins\" = \"XFMTX プラグインを全て削除\"\n"
    "\"Remove selected plug-in from list\" = \"選択したプラグインをリストから削除\"\n"
    "\"Remove any plug-ins whose files no longer exist\" = \"存在しないファイルのプラグインを削除\"\n"
    "\"Show folder containing selected plug-in\" = \"選択したプラグインのフォルダを開く\"\n"
    "\"Show folder containing plug-in\" = \"プラグインのフォルダを開く\"\n"
    "\"Scan for new or updated XFMTX plug-ins\" = \"新規/更新の XFMTX プラグインをスキャン\"\n"
    "\"Remove plug-in from list\" = \"プラグインをリストから削除\"\n"
    "\"Options...\" = \"オプション...\"\n"
    "\"Deactivated after failing to initialise correctly\" = \"初期化失敗のため無効化\"\n"
    "\"Select folders to scan...\" = \"スキャンするフォルダを選択...\"\n"
    "\"Scan\" = \"スキャン\"\n"
    "\"Cancel\" = \"キャンセル\"\n"
    "\"OK\" = \"OK\"\n"
    "\"Plugin Scanning\" = \"プラグインスキャン\"\n"
    "\"If you choose to scan folders that contain non-plugin files, \" = \"プラグイン以外のファイルを含むフォルダをスキャンすると、\"\n"
    "\"then scanning may take a long time, and can cause crashes when attempting to load unsuitable files.\" = \"時間がかかったり、不適切なファイルの読込時にクラッシュする恐れがあります。\"\n"
    "\"Are you sure you want to scan the folder \\\"XYZ\\\"?\" = \"フォルダ \\\"XYZ\\\" を本当にスキャンしますか？\"\n"
    "\"Testing\" = \"検証中\"\n"
    "\"Scanning for plug-ins...\" = \"プラグインをスキャン中...\"\n"
    "\"Searching for all possible plug-in files...\" = \"プラグインファイルを探索中...\"\n"
    "\"The following files encountered fatal errors during validation\" = \"以下のファイルは検証中に致命的なエラーが発生しました\"\n"
    "\"The following files appeared to be plugin files, but failed to load correctly\" = \"以下のファイルはプラグインに見えますが、正しく読込めませんでした\"\n"
    "\"Scan complete\" = \"スキャン完了\"\n"
    // テーブルヘッダ
    "\"Name\" = \"名前\"\n"
    "\"Format\" = \"フォーマット\"\n"
    "\"Category\" = \"カテゴリ\"\n"
    "\"Manufacturer\" = \"メーカー\"\n"
    "\"Description\" = \"説明\"\n"
    // ── AudioDeviceSelectorComponent ──
    "\"Output\" = \"出力\"\n"
    "\"Input\" = \"入力\"\n"
    "\"Device:\" = \"デバイス:\"\n"
    "\"Sample rate:\" = \"サンプルレート:\"\n"
    "\"Audio buffer size:\" = \"バッファサイズ:\"\n"
    "\"Active output channels:\" = \"出力チャンネル:\"\n"
    "\"Active input channels:\" = \"入力チャンネル:\"\n"
    "\"Show this device's control panel\" = \"このデバイスのコントロールパネルを開く\"\n"
    "\"Opens the device's own control panel\" = \"デバイスのコントロールパネルを開きます\"\n"
    "\"Test\" = \"テスト\"\n"
    "\"Plays a test tone, to check the output channel\" = \"出力チャンネルの確認用にテスト音を再生します\"\n"
    "\"No MIDI inputs available\" = \"使用可能な MIDI 入力がありません\"\n"
    "\"Active MIDI inputs:\" = \"アクティブな MIDI 入力:\"\n"
    "\"MIDI Output:\" = \"MIDI 出力:\"\n"
    "\"<< none >>\" = \"<< なし >>\"\n";

// アプリの日本語文言 → 英語の翻訳テーブル。
// キーは tr(u8"...") に渡す日本語文字列と完全一致させる (末尾スペース・改行も含む)。
// 記号のみ (♭ ♯ ⌘E Oct▲ 等) やすでに英語の文字列はフォールバックに任せて省略。
static const char* const englishTranslations =
    "language: English\n"
    "countries: us gb\n"
    "\n"
    // ── トランスポート / ツールバー ──
    "\"再生/停止\" = \"Play / Stop\"\n"
    "\"再生 / 停止\" = \"Play / Stop\"\n"
    "\"停止\" = \"Stop\"\n"
    "\"録音\" = \"Record\"\n"
    "\"録音切替\" = \"Toggle record\"\n"
    // ── 録音の準備 (アーム済みトラックが無いまま R を押したときの案内) ──
    "\"録音の準備\" = \"Recording setup\"\n"
    "\"このトラックを録音状態にして録音を開始しますか？\" = \"Arm this track for recording and start?\"\n"
    "\"録音する\" = \"Record\"\n"
    "\"録音できる空のトラックがありません。\\n新規トラックを追加してください。\" = \"There is no empty track to record on.\\nPlease add a new track.\"\n"
    "\"トランスポートの再生切替\" = \"Toggle play\"\n"
    "\"ループ再生のオン/オフ\" = \"Loop on/off\"\n"
    "\"横方向を拡大 (再生バー中心)\" = \"Zoom in (around playhead)\"\n"
    "\"横方向を縮小 (再生バー中心)\" = \"Zoom out (around playhead)\"\n"
    "\"横ズームをリセット (全体表示)\" = \"Reset horizontal zoom (fit project)\"\n"
    "\"波形振幅を拡大\" = \"Increase waveform amplitude\"\n"
    "\"波形振幅を縮小\" = \"Decrease waveform amplitude\"\n"
    "\"波形振幅をリセット\" = \"Reset waveform amplitude\"\n"
    "\"クリックでタップ計測ウィンドウを開く（TAP ボタン連打で計測）\" = \"Open tap tempo window (tap the TAP button)\"\n"
    "\"タップでテンポを検出\" = \"Detect tempo by tapping\"\n"
    "\"TAP ボタンを拍に合わせて連打\\n（やり直す場合は Reset）\" = \"Tap the TAP button in time\\n(press Reset to start over)\"\n"
    "\"タップ: \" = \"Taps: \"\n"
    "\"タップ: 0\" = \"Taps: 0\"\n"
    "\"検出されたテンポ: \" = \"Detected tempo: \"\n"
    "\"リセット\" = \"Reset\"\n"
    // ── メニュー (ファイル / ヘルプ) ──
    "\"ファイル\" = \"File\"\n"
    "\"ヘルプ\" = \"Help\"\n"
    "\"新規プロジェクト\" = \"New Project\"\n"
    "\"新規プロジェクト...\" = \"New Project...\"\n"
    "\"開く...\" = \"Open...\"\n"
    "\"別の場所から開く...\" = \"Open from Another Location...\"\n"
    "\"プロジェクトを開く\" = \"Open Project\"\n"
    "\"既存のプロジェクト\" = \"Existing Project\"\n"
    "\"最近使ったプロジェクト\" = \"Recent Projects\"\n"
    "\"保存\" = \"Save\"\n"
    "\"別名で保存...\" = \"Save As...\"\n"
    "\"プロジェクトを保存\" = \"Save Project\"\n"
    "\"プロジェクトを閉じる\" = \"Close Project\"\n"
    "\"オーディオを読み込む...\" = \"Import Audio...\"\n"
    "\"MIDI を読み込む\" = \"Import MIDI\"\n"
    "\"MIDI を読み込む...\" = \"Import MIDI...\"\n"
    "\"MIDI を書き出す\" = \"Export MIDI\"\n"
    "\"MIDI を書き出す...\" = \"Export MIDI...\"\n"
    "\"「MIDI を書き出す」をファイルメニューに表示\" = \"Show Export MIDI in the File menu\"\n"
    "\"MIDI 編集の再生バーがビュー外へ出たら自動でページ送りする\" = \"Auto-page the MIDI editor when the playhead moves out of view\"\n"
    "\"書き出せる MIDI ノートがありません\" = \"There are no MIDI notes to export\"\n"
    "\"書き出し\" = \"Export\"\n"
    "\"書き出し...\" = \"Export...\"\n"
    "\"プラグインを管理...\" = \"Manage Plugins...\"\n"
    "\"ショートカット一覧\" = \"Keyboard Shortcuts\"\n"
    "\"ショートカット一覧...\" = \"Keyboard Shortcuts...\"\n"
    "\"使い方ドキュメント...\" = \"User Guide...\"\n"
    "\"開発を支援する (寄付)...\" = \"Support Development (Donate)...\"\n"
    "\"ドキュメントファイル (help.html) が見つかりませんでした。\" = \"The documentation file (help.html) could not be found.\"\n"
    "\"Utawave について\" = \"About Utawave\"\n"
    "\"Utawave について...\" = \"About Utawave...\"\n"
    "\"環境設定\" = \"Preferences\"\n"
    "\"環境設定 (Cmd+,)\" = \"Preferences (Cmd+,)\"\n"
    // ── 起動画面 ──
    "\"プロジェクトを作成または開く\" = \"Create or open a project\"\n"
    "\"作成\" = \"Create\"\n"
    "\"プロジェクト名\" = \"Project name\"\n"
    "\"保存先\" = \"Location\"\n"
    "\"保存先フォルダを選択\" = \"Choose destination folder\"\n"
    "\"参照...\" = \"Browse...\"\n"
    // ── トラックヘッダ / ミキサー ──
    "\"音量\" = \"Volume\"\n"
    "\"パン\" = \"Pan\"\n"
    "\"音色\" = \"Tone\"\n"
    "\"モノ\" = \"Mono\"\n"
    "\"ステレオ\" = \"Stereo\"\n"
    "\"モノラルトラックを追加\" = \"Add Mono Track\"\n"
    "\"ステレオトラックを追加\" = \"Add Stereo Track\"\n"
    "\"MIDI トラックを追加\" = \"Add MIDI Track\"\n"
    "\"クリックトラックを追加\" = \"Add Click Track\"\n"
    "\"トラックを削除\" = \"Delete Track\"\n"
    "\"選択中のトラックを削除\" = \"Delete selected tracks\"\n"
    "\" 個のトラックを削除します。\\nこの操作は取り消せません。\" = \" tracks will be deleted.\\nThis cannot be undone.\"\n"
    "\"トラックを複製\" = \"Duplicate Track\"\n"
    "\"トラックカラー\" = \"Track Color\"\n"
    "\"インサート FX\" = \"Insert FX\"\n"
    "\"挿入\" = \"Insert\"\n"
    "\"バイパス\" = \"Bypass\"\n"
    "\"バイパスを解除\" = \"Un-bypass\"\n"
    "\"（バイパス中）\" = \"(bypassed)\"\n"
    "\"エディタを開く\" = \"Open Editor\"\n"
    "\"上のスロットへ移動\" = \"Move to Slot Above\"\n"
    "\"下のスロットへ移動\" = \"Move to Slot Below\"\n"
    "\"クリックでプラグインを追加\" = \"Click to add a plugin\"\n"
    "\"INS スロットを表示\" = \"Show INS slots\"\n"
    "\"INS スロットを非表示\" = \"Hide INS slots\"\n"
    "\"マスターパネルを折りたたむ\" = \"Collapse master panel\"\n"
    "\"プラグインがありません\" = \"No plugins\"\n"
    // ── 内蔵シンセ / MIDI トラック ──
    "\"クリック: 波形切替 / 右クリック または Cmd+クリック: 内蔵シンセを OFF\" = \"Click: change waveform / Right-click or Cmd+click: turn synth OFF\"\n"
    "\"内蔵シンセ OFF 中。右クリック または Cmd+クリックで ON に戻す\" = \"Built-in synth OFF. Right-click or Cmd+click to turn ON\"\n"
    // ── メトロノーム ──
    "\"メトロノーム設定\" = \"Metronome Settings\"\n"
    "\"アクセント\" = \"Accent\"\n"
    "\"頭の拍を強くする\" = \"Accent the first beat\"\n"
    // ── BPM / 拍子 / テンポ検出 ──
    "\"BPM の設定\" = \"Set BPM\"\n"
    "\"拍子の設定\" = \"Set Time Signature\"\n"
    "\"分子\" = \"Numerator\"\n"
    "\"分母\" = \"Denominator\"\n"
    "\"テンポ: \" = \"Tempo: \"\n"
    "\"テンポを検出\" = \"Detect Tempo\"\n"
    "\"テンポ検出\" = \"Tempo Detection\"\n"
    "\"テンポを検出中…\" = \"Detecting tempo…\"\n"
    "\"テンポを検出できませんでした。\\nクリップが短すぎるか、明確なビートが見つかりません。\" = \"Could not detect tempo.\\nThe clip is too short or has no clear beat.\"\n"
    "\"このテンポ変更を削除\" = \"Delete this tempo change\"\n"
    "\"この拍子変更を削除\" = \"Delete this time-signature change\"\n"
    // ── マーカー / ループ ──
    "\"ここにマーカーを追加\" = \"Add Marker Here\"\n"
    "\"このマーカーを削除\" = \"Delete This Marker\"\n"
    "\"全マーカーをクリア\" = \"Clear All Markers\"\n"
    "\"マーカーに色を表示\" = \"Show Marker Colors\"\n"
    "\"名前を変更\" = \"Rename\"\n"
    "\"色\" = \"Color\"\n"
    "\"ループ範囲\" = \"Loop Range\"\n"
    "\"ループ範囲をクリア\" = \"Clear Loop Range\"\n"
    "\"小節範囲\" = \"Bar Range\"\n"
    "\"開始小節\" = \"Start bar\"\n"
    "\"終了小節\" = \"End bar\"\n"
    // ── 編集 / クリップ ──
    "\"範囲選択\" = \"Range Select\"\n"
    "\"クリップ結合 (Consolidate)\" = \"Consolidate Clips\"\n"
    "\"クロスフェードを描く\" = \"Create Crossfade\"\n"
    "\"クリップゲイン: \" = \"Clip gain: \"\n"
    "\"トラック Vol: \" = \"Track Vol: \"\n"
    "\"フェードインカーブ\" = \"Fade-In Curve\"\n"
    "\"フェードアウトカーブ\" = \"Fade-Out Curve\"\n"
    "\"境界フェード\" = \"Boundary Fade\"\n"
    "\"リニア\" = \"Linear\"\n"
    "\"対数 (+3dB)\" = \"Logarithmic (+3dB)\"\n"
    "\"等パワー (-3dB)\" = \"Equal Power (-3dB)\"\n"
    "\"S字\" = \"S-Curve\"\n"
    "\"このテイクを使う\" = \"Use This Take\"\n"
    "\"キーを変更...\" = \"Change Key...\"\n"
    "\"キーを \" = \"Pitch by \"\n"
    "\" 半音\" = \" semitones\"\n"
    "\"0 (元の音程)\" = \"0 (original pitch)\"\n"
    // ── 無音区間カット ──
    "\"無音区間をカット\" = \"Strip Silence\"\n"
    "\"無音区間をカット...\" = \"Strip Silence...\"\n"
    "\"無音区間なし\" = \"No silent regions\"\n"
    "\"指定条件で無音区間は見つかりませんでした。\" = \"No silent regions found with the given settings.\"\n"
    "\"クリップ全体が無音と判定されました。実行を中止します。\" = \"The entire clip was detected as silent. Aborting.\"\n"
    "\"全体が無音\" = \"Entire clip silent\"\n"
    "\"最短無音時間\" = \"Minimum silence length\"\n"
    "\"閾値 (dB)\" = \"Threshold (dB)\"\n"
    "\"ゲインエンベロープを破棄しますか?\" = \"Discard the gain envelope?\"\n"
    "\"このクリップにはボリュームエンベロープが設定されています。\\n\" = \"This clip has a volume envelope.\\n\"\n"
    "\"クリップゲインのみ反映\" = \"Apply clip gain only\"\n"
    "\"破棄\" = \"Discard\"\n"
    // ── 選択 / 共通操作 ──
    "\"全選択\" = \"Select All\"\n"
    "\"全解除\" = \"Deselect All\"\n"
    "\"選択を削除\" = \"Delete Selection\"\n"
    "\"削除\" = \"Delete\"\n"
    "\"クリック/移動ツールのみ\" = \"Click/Move tool only\"\n"
    "\"範囲選択ツールのみ\" = \"Range-select tool only\"\n"
    "\"グリッドスナップ（クリックで Off/Bar/Beat 切替）\" = \"Grid snap (click to cycle Off/Bar/Beat)\"\n"
    "\"クリップゲインラインを表示（ブレークポイント編集可能）\" = \"Show clip gain line (editable breakpoints)\"\n"
    "\"リンク: 両方のツールを併用（スマートツール）\" = \"Linked: smart tool (both)\"\n"
    // ── 環境設定 ──
    "\"言語 (Language)  ※再起動で反映\" = \"Language  *applies after restart\"\n"
    "\"言語設定\" = \"Language\"\n"
    "\"言語の変更は次回起動時に反映されます。\" = \"The language change will take effect the next time you start the app.\"\n"
    "\"インポート時のリサンプル出力\" = \"Resample output on import\"\n"
    "\"インポート時に不要なタグを削除する (テンポ等の埋め込み情報)\" = \"Strip unnecessary tags on import (embedded tempo, etc.)\"\n"
    "\"32bit float（推奨）: ディザ不要・最高音質\\n\" = \"32-bit float (recommended): no dither, best quality\\n\"\n"
    "\"編集動作\" = \"Editing Behavior\"\n"
    "\"録音フロー\" = \"Recording\"\n"
    "\"自動保存\" = \"Auto-Save\"\n"
    "\"バックアップを残す数 (古い世代から自動削除)\" = \"Backups to keep (oldest deleted automatically)\"\n"
    "\"VU メータ基準レベル (0 VU)\" = \"VU meter reference level (0 VU)\"\n"
    "\"ラウドネス自動調整ターゲット\" = \"Loudness normalization target\"\n"
    "\"再生バーを選択先頭に追従させる (Insertion Follows Selection)\" = \"Insertion follows selection\"\n"
    "\"停止時に再生開始位置へ戻る (Return To Zero)\" = \"Return to start position on stop (RTZ)\"\n"
    "\"Cmd+スクロール拡大の起点をマウス位置にする (OFF: 再生バー中央)\" = \"Cmd+scroll zoom centers on mouse (OFF: playhead)\"\n"
    "\"再生中バックグラウンド録音 (遡及録音 Cmd+Shift+R で確定)\" = \"Background recording while playing (commit retrospective with Cmd+Shift+R)\"\n"
    "\"録音をデバイスのレイテンシ分だけ自動で手前にずらす\" = \"Auto-compensate recording latency reported by the device\"\n"
    "\"追加の録音補正 (ms, +で手前へ)\" = \"Extra recording offset (ms, + = earlier)\"\n"
    "\"入力モニター中、トラックの INS (インサート FX) を返し音にも通す\" = \"Run the track's INS (insert FX) on the input-monitor return too\"\n"
    "\"インポート時にラウドネスを上記ターゲットへ自動調整\" = \"Auto-adjust loudness to the target above on import\"\n"
    "\"ピーク超過時に内部で減衰させて書き出す (クリッピング防止)\" = \"Attenuate on peak overshoot when exporting (prevents clipping)\"\n"
    "\"デフォルトに戻す\" = \"Restore Defaults\"\n"
    "\"設定リセット\" = \"Reset Settings\"\n"
    "\"全ての環境設定をデフォルト値に戻します。よろしいですか？\" = \"Restore all preferences to their default values?\"\n"
    "\"無効\" = \"Off\"\n"
    "\"10 分\" = \"10 min\"\n"
    "\"15 分\" = \"15 min\"\n"
    "\"20 分\" = \"20 min\"\n"
    "\"25 分\" = \"25 min\"\n"
    "\"30 分\" = \"30 min\"\n"
    "\"5 分\" = \"5 min\"\n"
    "\"5 個\" = \"5\"\n"
    "\"10 個\" = \"10\"\n"
    "\"20 個\" = \"20\"\n"
    "\"30 個\" = \"30\"\n"
    "\"50 個\" = \"50\"\n"
    "\"100 個\" = \"100\"\n"
    // ── オーディオ設定 ──
    "\"オーディオI/F\" = \"Audio Device\"\n"
    "\"オーディオI/F の設定\" = \"Audio Device Settings\"\n"
    "\"サンプリングレート\" = \"Sample rate\"\n"
    "\"サンプルレート\" = \"Sample rate\"\n"
    "\"ビット深度\" = \"Bit depth\"\n"
    "\"出力チャンネル\" = \"Output channel\"\n"
    "\"オーディオエンジンが起動していません\" = \"The audio engine is not running\"\n"
    "\" にオーディオデバイスを設定できませんでした。\\n\\n\" = \" : could not configure the audio device.\\n\\n\"\n"
    // ── プラグイン管理 ──
    "\"プラグイン管理\" = \"Plugin Manager\"\n"
    "\"プラグインをスキャン\" = \"Scan plugins\"\n"
    "\"全て再スキャン\" = \"Rescan All\"\n"
    "\"全プラグイン再スキャン開始...\" = \"Starting full plugin rescan...\"\n"
    "\"スキャン開始...\" = \"Starting scan...\"\n"
    "\"スキャン中...\" = \"Scanning...\"\n"
    "\"スキャン完了\" = \"Scan complete\"\n"
    "\"スキャンするフォルダを追加\" = \"Add folder to scan\"\n"
    "\"検索パス...\" = \"Search Paths...\"\n"
    "\"検証中: \" = \"Validating: \"\n"
    "\"リストをクリア\" = \"Clear List\"\n"
    "\"名前\" = \"Name\"\n"
    "\"フォーマット\" = \"Format\"\n"
    "\"カテゴリ\" = \"Category\"\n"
    "\"メーカー\" = \"Manufacturer\"\n"
    "\"このプラグインは独自エディタを持っていません\" = \"This plugin has no custom editor\"\n"
    "\"プラグインの読込に失敗\" = \"Failed to load plugin\"\n"
    "\"プラグインのコピーに失敗\" = \"Failed to copy plugin\"\n"
    "\"「ファイル」→「プラグインを管理...」でスキャンを実行してください\" = \"Run a scan from File -> Manage Plugins...\"\n"
    // ── MIDI インポート ──
    "\"MIDI ファイルを選択\" = \"Select a MIDI file\"\n"
    "\"SMF を解析できません\" = \"Cannot parse the MIDI file\"\n"
    "\"テンポ・拍子も取り込む\" = \"Import tempo & time signature\"\n"
    "\"マーカーも取り込む\" = \"Import markers\"\n"
    "\"(Drum)\" = \"(Drum)\"\n"
    // ── 書き出し ──
    "\"書き出しモード\" = \"Export mode\"\n"
    "\"ミックスダウン\" = \"Mixdown\"\n"
    "\"トラック書き出し\" = \"Export Stems\"\n"
    "\"書き出すトラック\" = \"Tracks to export\"\n"
    "\"書き出すトラックを選択してください\" = \"Please select tracks to export\"\n"
    "\"書き出せるトラックがありません\" = \"There are no exportable tracks\"\n"
    "\"プロジェクト全体\" = \"Whole project\"\n"
    "\"範囲\" = \"Range\"\n"
    "\"ファイル名（拡張子なし）\" = \"File name (no extension)\"\n"
    "\"出力フォルダ\" = \"Output folder\"\n"
    "\"出力フォルダを選択\" = \"Choose output folder\"\n"
    "\"出力フォルダを指定してください\" = \"Please specify an output folder\"\n"
    "\"出力フォルダ未指定\" = \"No output folder specified\"\n"
    "\"MP3 ビットレート\" = \"MP3 bitrate\"\n"
    "\"TPDFディザ (16/24bit)\" = \"TPDF dither (16/24-bit)\"\n"
    "\"16/24bit で書き出すときに加える微小なノイズです。量子化で生じるざらつき（特にフェードや小音量部の歪み）を聞こえにくい滑らかなノイズに変え、より自然な音にします。通常はオンのまま推奨。32bit float では不要なため自動でオフになります。\" = \"Adds tiny noise when exporting to 16/24-bit. It turns the roughness from quantization (distortion in fades and quiet passages especially) into smoother, less audible noise for a more natural sound. Leave it on in most cases. Not needed for 32-bit float, so it turns off automatically.\"\n"
    "\"同名ファイルがある場合は自動連番\" = \"Auto-number when a file of the same name exists\"\n"
    "\"完了後に出力フォルダを開く\" = \"Open output folder when done\"\n"
    "\"実時間レンダリング（一部プラグインの互換用、再生長と同じ時間がかかります）\" = \"Real-time render (for plugin compatibility; takes as long as playback)\"\n"
    "\"書き出し中...\" = \"Exporting...\"\n"
    "\"書き出し中: \" = \"Exporting: \"\n"
    "\"書き出し完了\" = \"Export complete\"\n"
    "\"書き出しが完了しました:\\n\" = \"Export complete:\\n\"\n"
    "\"書き出し失敗\" = \"Export failed\"\n"
    "\"書き出しに失敗しました\" = \"Export failed\"\n"
    "\"書き出し対象なし\" = \"Nothing to export\"\n"
    "\"書き出し範囲が無効です\" = \"Invalid export range\"\n"
    "\"トラック書き出しが完了しました（\" = \"Stem export complete (\"\n"
    "\"MP3 書き出しに失敗しました: \" = \"MP3 export failed: \"\n"
    "\"出力ファイルを開けません\" = \"Cannot open the output file\"\n"
    "\"出力ファイルへの書き込みに失敗しました (ディスク容量を確認してください)\" = \"Failed to write the output file (check free disk space)\"\n"
    "\"録音を開始できないトラックがあります\" = \"Some tracks could not start recording\"\n"
    "\"前回終了時に問題が発生しました\" = \"A problem occurred last time\"\n"
    "\"クラッシュログが保存されています。内容を確認しますか？\" = \"A crash log was saved. Would you like to review it?\"\n"
    "\"ログを表示\" = \"Show Log\"\n"
    "\"アプリの改善のため、エラーログを開発者に送信してもよろしいですか？\\nログにはクラッシュ時の技術情報 (スタックトレース・アプリのバージョン・OS) のみが含まれ、\\n音声データや個人情報は含まれません。\" = \"To help improve the app, may we send the error log to the developer?\\nThe log only contains technical crash details (stack trace, app version, OS) -\\nno audio data or personal information is included.\"\n"
    "\"送信する\" = \"Send\"\n"
    "\"送信しない\" = \"Don't Send\"\n"
    "\"送信できませんでした\" = \"Could not send\"\n"
    "\"エラーログを送信できませんでした。\\nインターネット接続を確認してください (ログはローカルに残っています)。\" = \"The error log could not be sent.\\nPlease check your internet connection (the log is kept locally).\"\n"
    "\"以下のトラックの録音ファイルを作成できませんでした。\\nディスクの空き容量と書き込み権限を確認してください。\\n\\n\" = \"Could not create recording files for the following tracks.\\nCheck free disk space and write permissions.\\n\\n\"\n"
    "\"ライターを作成できません\" = \"Cannot create the writer\"\n"
    "\"前パディング\" = \"Pre-padding\"\n"
    "\"後パディング\" = \"Post-padding\"\n"
    // ── ラウドネス測定 ──
    "\"ラウドネス測定\" = \"Loudness Measurement\"\n"
    "\"ラウドネス調整\" = \"Loudness Adjustment\"\n"
    "\"現在のラウドネス: \" = \"Current loudness: \"\n"
    "\"ターゲット: \" = \"Target: \"\n"
    "\"このトラックには測定可能なクリップがありません。\" = \"This track has no measurable clips.\"\n"
    "\"ラウドネスを測定できませんでした。\\nクリップが短すぎるか、無音が多すぎます。\" = \"Could not measure loudness.\\nThe clip is too short or too silent.\"\n"
    "\" LUFS に合わせる\" = \" : normalize to this LUFS\"\n"
    "\"トラックVol/Pan/マスターまで反映\" = \"Apply through track Vol/Pan/Master\"\n"
    "\"\\n※ Vol の上限/下限により制限されました\" = \"\\n* Limited by the Vol min/max range\"\n"
    "\"\\n\\n適用しますか?\" = \"\\n\\nApply?\"\n"
    // ── プロジェクト管理 / 保存 / 復旧 ──
    "\"このプロジェクトには未保存の変更があります。\\n保存しますか?\" = \"This project has unsaved changes.\\nDo you want to save?\"\n"
    "\"保存しない\" = \"Don't Save\"\n"
    "\"変更を保存しますか?\" = \"Save changes?\"\n"
    "\"前回終了時に未保存の変更が見つかりました。\\n自動保存ファイルから復旧しますか?\" = \"Unsaved changes were found from the last session.\\nRecover from the auto-save file?\"\n"
    "\"復旧\" = \"Recover\"\n"
    "\"自動保存から復旧\" = \"Recover from Auto-Save\"\n"
    "\"保存失敗\" = \"Save failed\"\n"
    "\"保存先エラー\" = \"Destination error\"\n"
    "\"保存先フォルダを作成できませんでした\" = \"Could not create the destination folder\"\n"
    "\"プロジェクトの保存に失敗しました: \" = \"Failed to save the project: \"\n"
    "\"読み込み失敗\" = \"Load failed\"\n"
    "\"プロジェクトを読み込めませんでした: \" = \"Could not load the project: \"\n"
    "\"同名のプロジェクトが既に存在します。\\n別の名前を指定してください。\" = \"A project with the same name already exists.\\nPlease choose another name.\"\n"
    "\"欠損ファイル\" = \"Missing Files\"\n"
    "\"以下の音声ファイルが見つかりませんでした。\\n\" = \"The following audio files could not be found.\\n\"\n"
    "\"クリップを読み込めませんでした。\" = \"Could not load the clip.\"\n"
    "\"ファイルが見つかりません\" = \"File not found\"\n"
    "\"ファイルを開けません\" = \"Cannot open file\"\n"
    "\"未対応フォーマット\" = \"Unsupported format\"\n"
    "\"リサンプル失敗: \" = \"Resample failed: \"\n"
    "\"同名のファイルが既に存在します\" = \"A file with the same name already exists\"\n"
    // ── インポート / 配置 ──
    "\"オーディオを読み込む...\" = \"Import Audio...\"\n"
    "\"オーディオファイルを選択\" = \"Select an audio file\"\n"
    "\"インポート失敗\" = \"Import failed\"\n"
    "\"インポート中...\" = \"Importing...\"\n"
    "\"インポート中: \" = \"Importing: \"\n"
    "\"先頭に配置\" = \"Place at start\"\n"
    "\"現在の再生位置に配置\" = \"Place at playhead\"\n"
    // ── ステータスバー / 波形ロード ──
    "\"トラック数: \" = \"Tracks: \"\n"
    "\"波形を読み込み中… \" = \"Loading waveforms... \"\n"
    "\"波形の読み込みが完了しました\" = \"Waveform loading complete\"\n"
    // ── About ──
    "\"バージョン \" = \"Version \"\n"
        "\"ライセンス情報 / 利用しているオープンソース\" = \"License / Open-source acknowledgements\"\n"
    "\"本アプリは AGPL v3 ライセンスの下で配布されています。\\n\" = \"This app is distributed under the AGPL v3 license.\\n\"\n"
    "\"ソースコードは公式サイトで公開しています。\\n\" = \"The source code is available on the official website.\\n\"\n"
    "\"── 免責事項 ──\\n\" = \"── Disclaimer ──\\n\"\n"
    "\"本ソフトウェアは無料で「現状のまま」提供されます。万一、使用（または使用できないこと）により損害が生じた場合でも、作者は責任を負いかねます。大切なデータはバックアップしてください。(詳細は AGPL v3 第15条・第16条)\\n\\n\" = \"This software is free and provided AS IS. The author cannot accept liability for damages arising from the use of, or inability to use, this software. Please back up important data. (See Sections 15 and 16 of the AGPL v3 for details)\\n\\n\"\n"
    "\"開発を応援する (寄付):\\n\" = \"Support development (donations):\\n\"\n"
    "\"https://donate.stripe.com/8x29ATdTI6g07vo49S38404\" = \"https://donate.stripe.com/fZubJ16rg5bW9Dw9uc38405\"\n"
    // ── 共通ボタン / ダイアログ ──
    "\"キャンセル\" = \"Cancel\"\n"
    "\"閉じる\" = \"Close\"\n"
    "\"続行\" = \"Continue\"\n"
    "\"適用\" = \"Apply\"\n"
    "\"適用しますか?\" = \"Apply?\"\n"
    "\"プロジェクトに適用しますか?\" = \"Apply to the project?\"\n"
    "\"変更...\" = \"Change...\"\n"
    "\"なし\" = \"None\"\n"
    "\"未選択\" = \"None selected\"\n"
    "\"トラック未選択\" = \"No track selected\"\n"
    // ── ピアノロール ──
    "\"ピアノロールを開く\" = \"Open Piano Roll\"\n"
    "\"ノート:\" = \"Note:\"\n"
    "\"長さ: \" = \"Length: \"\n"
    "\" 秒\" = \" sec\"\n"
    "\"1 小節\" = \"1 bar\"\n"
    "\"2 小節\" = \"2 bars\"\n"
    "\"4 小節\" = \"4 bars\"\n"
    "\"小節\" = \"bar\"\n"
    "\"小節を表示\" = \"Show bars\"\n"
    "\"小節を非表示\" = \"Hide bars\"\n"
    "\"時刻を表示\" = \"Show time\"\n"
    "\"時刻を非表示\" = \"Hide time\"\n"
    // ── ショートカット一覧: セクション見出し ──
    "\"トランスポート\" = \"Transport\"\n"
    "\"編集\" = \"Edit\"\n"
    "\"トラック\" = \"Track\"\n"
    "\"マーカー / ナビゲーション\" = \"Markers / Navigation\"\n"
    "\"グリッド (スナップ)\" = \"Grid (Snap)\"\n"
    "\"表示・ナビゲーション\" = \"View & Navigation\"\n"
    "\"ルーラー\" = \"Ruler\"\n"
    // ── ショートカット一覧: キー列 (日本語を含むもの) ──
    "\"Cmd+スクロール\" = \"Cmd+Scroll\"\n"
    "\"Shift+Option+スクロール\" = \"Shift+Option+Scroll\"\n"
    "\"Cmd+クリック\" = \"Cmd+Click\"\n"
    "\"Alt+クリック\" = \"Alt+Click (Option)\"\n"
    "\"Cmd+クリック (テンポ列)\" = \"Cmd+Click (tempo row)\"\n"
    "\"Cmd+クリック (拍子列)\" = \"Cmd+Click (meter row)\"\n"
    "\"Cmd+ホールド + ルーラー\" = \"Cmd+Hold + ruler\"\n"
    "\"右クリック (マーカー / テンポ / 拍子上)\" = \"Right-click (on marker / tempo / meter)\"\n"
    // ── ショートカット一覧: アクション列 ──
    "\"録音 開始 / 停止 (パンチイン対応)\" = \"Start / stop recording (punch-in)\"\n"
    "\"遡及録音を確定\" = \"Commit retrospective recording\"\n"
    "\"ループ再生 ON / OFF\" = \"Loop playback on / off\"\n"
    "\"先頭へ戻る\" = \"Return to start\"\n"
    "\"オーディオファイル取り込み\" = \"Import audio file\"\n"
    "\"別名で保存\" = \"Save As\"\n"
    "\"取り消し / やり直し\" = \"Undo / Redo\"\n"
    "\"クリップ全選択\" = \"Select all clips\"\n"
    "\"コピー / カット / ペースト\" = \"Copy / Cut / Paste\"\n"
    "\"複製\" = \"Duplicate\"\n"
    "\"選択クリップ / クロスフェード削除\" = \"Delete selected clip / crossfade\"\n"
    "\"クリップを左右にナッジ\" = \"Nudge clip left / right\"\n"
    "\"選択範囲で fade-in / fade-out\" = \"Fade-in / fade-out over selection\"\n"
    "\"選択範囲でクロスフェード\" = \"Crossfade over selection\"\n"
    "\"クリップ分割 / プラグインバイパス\" = \"Split clip / bypass plugin\"\n"
    "\"クリップ分割 (波形 / MIDI のカット)\" = \"Split clip (cut audio / MIDI)\"\n"
    "\"プラグインをバイパス (INS チップ)\" = \"Bypass plugin (INS chip)\"\n"
    "\"録音アーム トグル\" = \"Toggle record arm\"\n"
    "\"ソロ トグル\" = \"Toggle solo\"\n"
    "\"ミュート トグル\" = \"Toggle mute\"\n"
    "\"入力モニター トグル\" = \"Toggle input monitor\"\n"
    "\"テイクレーン (TList) 表示切替\" = \"Toggle take lanes (TList)\"\n"
    "\"テイクから Lane 0 へ採用\" = \"Promote take to Lane 0\"\n"
    "\"1 小節 進む / 戻る\" = \"Move 1 bar forward / back\"\n"
    "\"再生バーを進む / 戻る\" = \"Move playhead forward / back\"\n"
    "\"次 / 前のマーカーへジャンプ\" = \"Jump to next / previous marker\"\n"
    "\"グリッド Off\" = \"Grid Off\"\n"
    "\"1/1 (小節)\" = \"1/1 (bar)\"\n"
    "\"1/2 (二分音符)\" = \"1/2 (half note)\"\n"
    "\"1/4 (四分音符)\" = \"1/4 (quarter note)\"\n"
    "\"1/8 (八分音符)\" = \"1/8 (eighth note)\"\n"
    "\"1/16 (十六分音符)\" = \"1/16 (sixteenth note)\"\n"
    "\"1/32 (三十二分音符)\" = \"1/32 (thirty-second note)\"\n"
    "\"1/4 三連\" = \"1/4 triplet\"\n"
    "\"1/8 三連\" = \"1/8 triplet\"\n"
    "\"1/16 三連\" = \"1/16 triplet\"\n"
    "\"横ズーム (再生バー中央 / マウス位置)\" = \"Horizontal zoom (playhead / mouse)\"\n"
    "\"波形振幅 縦ズーム\" = \"Vertical waveform zoom\"\n"
    "\"プロジェクト全体ビューに合わせる\" = \"Fit project to view\"\n"
    "\"テンポ変更を挿入\" = \"Insert tempo change\"\n"
    "\"拍子変更を挿入\" = \"Insert time-signature change\"\n"
    "\"ペンシルツール (記入準備)\" = \"Pencil tool (ready to draw)\"\n"
    "\"該当の削除メニュー\" = \"Context delete menu\"\n"
    "\"ループ範囲の開始 / 終了を設定\" = \"Set loop range start / end\"\n"
    "\"曲頭〜再生位置を範囲選択\" = \"Select from start to playhead\"\n"
    "\"クリップを大きくナッジ\" = \"Nudge clip (large step)\"\n"
    "\"選択範囲のフォーカスレーンを移動\" = \"Move focus lane of selection\"\n"
    "\"このショートカット一覧を表示\" = \"Show this shortcut list\"\n"
    "\"ショートカット\" = \"Shortcuts\"\n"
    "\"閉じる\" = \"Close\"\n"
    // ── GRID コンボ / メニュー (説明付き) ──
    "\"GRID: 1/4 三連\" = \"GRID: 1/4 T\"\n"
    "\"GRID: 1/8 三連\" = \"GRID: 1/8 T\"\n"
    "\"GRID: 1/16 三連\" = \"GRID: 1/16 T\"\n"
    "\"1/1    小節\" = \"1/1    bar\"\n"
    "\"1/2    二分音符\" = \"1/2    half note\"\n"
    "\"1/4    四分音符\" = \"1/4    quarter note\"\n"
    "\"1/8    八分音符\" = \"1/8    eighth note\"\n"
    "\"1/16   十六分音符\" = \"1/16   sixteenth note\"\n"
    "\"1/32   三十二分音符\" = \"1/32   thirty-second note\"\n"
    "\"1/4 T  四分三連\" = \"1/4 T  quarter triplet\"\n"
    "\"1/8 T  八分三連\" = \"1/8 T  eighth triplet\"\n"
    "\"1/16 T 十六分三連\" = \"1/16 T sixteenth triplet\"\n"
    // ── VU / ラウドネス コンボ項目 ──
    "\"-14 dBFS (配信向け)\" = \"-14 dBFS (streaming)\"\n"
    "\"-18 dBFS (EBU R68 / 放送)\" = \"-18 dBFS (EBU R68 / broadcast)\"\n"
    "\"-20 dBFS (SMPTE / ポスプロ)\" = \"-20 dBFS (SMPTE / post)\"\n"
    "\"-24 dBFS (映画向け)\" = \"-24 dBFS (film)\"\n"
    "\"-14 LUFS (Spotify / 配信)\" = \"-14 LUFS (Spotify / streaming)\"\n"
    "\"-18 LUFS (動画 / Web)\" = \"-18 LUFS (video / web)\"\n"
    "\"-23 LUFS (EBU R128 放送)\" = \"-23 LUFS (EBU R128 broadcast)\"\n"
    // ── カウントイン / プリロール ──
    "\"カウントイン (Pre-Roll と排他)\" = \"Count-in (exclusive with Pre-Roll)\"\n"
    "\"プリロール (Count-In と排他)\" = \"Pre-roll (exclusive with Count-In)\"\n"
    "\"Nothing (入力ペア無し)\" = \"Nothing (no input pair)\"\n"
    // ── その他の単独 UI 文言 ──
    "\"プロジェクト\" = \"Project\"\n"
    "\"プロジェクト保存\" = \"Save Project\"\n"
    "\"プロジェクトのサンプリングレート \" = \"Project sample rate \"\n"
    "\"読み込み\" = \"Open\"\n"
    "\"作成できません\" = \"Cannot create\"\n"
    "\"空のバッファ\" = \"Empty buffer\"\n"
    "\"範囲が無効です\" = \"Invalid range\"\n"
    "\"範囲エラー\" = \"Range error\"\n"
    // ── 連結断片 (前後に値が付く) ──
    "\"ノート:\" = \"Note:\"\n"
    "\"位置  \" = \"Pos  \"\n"
    "\" (コピー)\" = \" (copy)\"\n"
    "\"  (曲頭)\" = \"  (start)\"\n"
    "\"  ... ほか \" = \"  ... and \"\n"
    "\" 件\\n\" = \" more\\n\"\n"
    "\" へ変換中...\" = \" : converting...\"\n"
    "\"ラウドネスを \" = \"Loudness \"\n"
    // ── 残りの単独 UI 文言 ──
    "\"    テンポ: \" = \"    Tempo: \"\n"
    "\"    長さ: \" = \"    Length: \"\n"
    "\"   ノート:\" = \"   Note:\"\n"
    "\"1 秒\" = \"1 sec\"\n"
    "\"2 秒\" = \"2 sec\"\n"
    "\"3 秒\" = \"3 sec\"\n"
    "\"24bit PCM: TPDFディザ付き・ファイルサイズ約25%減\" = \"24-bit PCM: with TPDF dither, ~25% smaller files\"\n"
    "\"アクセント (Accent): 小節頭の 1 拍目だけ強めに鳴らす\" = \"Accent: emphasize the first beat of each bar\"\n"
    "\"キー変更\" = \"Change Key\"\n"
    "\"サンプリングレートはプロジェクト設定により固定されています\" = \"The sample rate is fixed by the project settings\"\n"
    "\"ピッチシフト処理に失敗しました。\" = \"Pitch shift failed.\"\n"
    "\"マスターパネルを展開\" = \"Expand master panel\"\n"
    "\"停止中... 現在のプラグイン処理完了を待っています（数秒かかります）\" = \"Stopping... waiting for current plugin processing to finish (this may take a few seconds)\"\n"
    "\"元の音程のファイルが見つかりませんでした。\" = \"The original-pitch file could not be found.\"\n"
    "\"既知のプラグインも含めて全て再スキャンします (バージョンアップ後の認識更新用)\" = \"Rescan all plugins including known ones (to refresh after updates)\"\n"
    "\"続行しますか?\" = \"Continue?\"\n"
    // ── About: ライセンス本文 ──
    "\"── 利用しているサードパーティ ライブラリ ──\\n\\n\" = \"── Third-party libraries used ──\\n\\n\"\n"
    "\"  AGPL v3 (非商用 / オープンソース利用)\\n\\n\" = \"  AGPL v3 (non-commercial / open-source use)\\n\\n\"\n"
    "\"ASIO Interface Technology  (Windows ビルド時のみ、任意)\\n\" = \"ASIO Interface Technology  (Windows build only, optional)\\n\"\n"
    "\"  デュアルライセンス (Steinberg ASIO License または GPL v3)\\n\" = \"  Dual license (Steinberg ASIO License or GPL v3)\\n\"\n"
    "\"  本プロジェクトでは GPL v3 の選択肢で利用\\n\" = \"  This project uses the GPL v3 option\\n\"\n"
    // ── 起動画面の広告枠 (AdPanel) / 環境設定 ──
    "\"広告\" = \"Sponsored\"\n"
    "\"広告を読み込み中...\" = \"Loading ads...\"\n"
    "\"広告を読み込めませんでした\" = \"Couldn't load ads\"\n"
    "\"現在表示できる広告はありません\" = \"No ads to show right now\"\n"
    "\"インターネット接続を確認してください\" = \"Please check your internet connection\"\n"
    "\"再読み込み\" = \"Reload\"\n"
    "\"詳しく見る ↗\" = \"Learn more ↗\"\n"
    "\"起動画面\" = \"Startup screen\"\n"
    "\"起動画面に広告を表示する (OFF で通信しません。次回起動で反映)\" = \"Show ads on the startup screen (no network when off; applies on next launch)\"\n"
    // ── アップデート通知 (起動画面右上のバナー) ──
    "\"アップデートがあります\" = \"Update available\"\n"
    "\"ダウンロードページを開く\" = \"Open the download page\"\n"
    // ── 内蔵エフェクト (EQ / コンプ / リバーブ) ──
    "\"内蔵EQ\" = \"EQ\"\n"
    "\"内蔵コンプ\" = \"Compressor\"\n"
    "\"内蔵リバーブ\" = \"Reverb\"\n"
    "\"エフェクトを複製できませんでした\" = \"Couldn't duplicate the effect\"\n"
    "\"プリセット\" = \"Preset\"\n"
    "\"選択...\" = \"Select...\"\n"
    // EQ パラメータ / プリセット
    "\"ローカット\" = \"Low Cut\"\n"
    "\"低域 Hz\" = \"Low Hz\"\n"
    "\"低域\" = \"Low\"\n"
    "\"中域 Hz\" = \"Mid Hz\"\n"
    "\"中域\" = \"Mid\"\n"
    "\"高域 Hz\" = \"High Hz\"\n"
    "\"高域\" = \"High\"\n"
    "\"フラット\" = \"Flat\"\n"
    "\"ボーカル明瞭\" = \"Vocal Clarity\"\n"
    "\"低域すっきり\" = \"Tighten Lows\"\n"
    "\"温かみ\" = \"Warmth\"\n"
    "\"ラジオ風\" = \"Radio\"\n"
    // コンプ パラメータ / プリセット
    "\"スレッショルド\" = \"Threshold\"\n"
    "\"レシオ\" = \"Ratio\"\n"
    "\"アタック\" = \"Attack\"\n"
    "\"リリース\" = \"Release\"\n"
    "\"メイクアップ\" = \"Makeup\"\n"
    "\"オフ\" = \"Off\"\n"
    "\"ボーカル軽め\" = \"Vocal Light\"\n"
    "\"ボーカルしっかり\" = \"Vocal Strong\"\n"
    "\"ナレーション\" = \"Narration\"\n"
    "\"リミッター風\" = \"Limiter\"\n"
    // リバーブ パラメータ / プリセット
    "\"ミックス\" = \"Mix\"\n"
    "\"広さ\" = \"Size\"\n"
    "\"ダンピング\" = \"Damping\"\n"
    "\"ステレオ幅\" = \"Width\"\n"
    "\"ボーカル\" = \"Vocal\"\n"
    "\"プレート\" = \"Plate\"\n"
    "\"ルーム\" = \"Room\"\n"
    "\"ホール\" = \"Hall\"\n"
    "\"薄く\" = \"Subtle\"\n";

void install(Language lang)
{
    const char* table = (lang == Language::English) ? englishTranslations
                                                     : japaneseTranslations;
    juce::LocalisedStrings::setCurrentMappings(
        new juce::LocalisedStrings(juce::String(juce::CharPointer_UTF8(table)),
                                   /*ignoreCaseOfKeys*/ false));
}

void installJapanese() { install(Language::Japanese); }

static juce::File languageStoreFile()
{
    auto root = juce::File::getSpecialLocation(juce::File::userApplicationDataDirectory)
                    .getChildFile("Utawave");
    root.createDirectory();
    return root.getChildFile("language.txt");
}

Language getSavedLanguage()
{
    auto f = languageStoreFile();
    if (f.existsAsFile())
    {
        // ユーザが明示的に選んだ言語を優先
        const auto txt = f.loadFileAsString().trim().toLowerCase();
        if (txt == "english" || txt == "en")    return Language::English;
        if (txt == "japanese" || txt == "ja")   return Language::Japanese;
    }
    // 初回起動 (未保存): システム言語に合わせる。日本語のみ日本語、それ以外は英語。
    const auto sys = juce::SystemStats::getUserLanguage().toLowerCase();
    return sys.startsWith("ja") ? Language::Japanese : Language::English;
}

void saveLanguage(Language lang)
{
    languageStoreFile().replaceWithText(lang == Language::English ? "english" : "japanese");
}

juce::String displayName(Language lang)
{
    return lang == Language::English ? "English" : juce::String::fromUTF8(u8"日本語");
}

} // namespace Localisation
